[package]

name = "vectors-starting"
version = "0.1.0"
authors = []

[[bin]]
name = "vectors-starting"

[dependencies]
piston = "0.23.0"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.27.0"
piston2d-opengl_graphics = "0.30.0"
num = "0.1.*"
nalgebra = "0.8.2"
